name: Provision Infrastructure

on:
  push:
    branches:
      - "main" 
    paths:
      - "TranscribeTranslateDemo.Infrastructure/**"
      - ".github/workflows/bicep.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  provision-azure-resources:
    runs-on: ubuntu-latest
    steps:

    # Log into Azure
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Empty Out Environment
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az cognitiveservices account delete --name ${{ vars.RESOURCE_NAME }}speech
          az cognitiveservices account purge --location centralus --resource-group ${{ vars.RESOURCE_NAME }} --name ${{ vars.RESOURCE_NAME }}speech
          az group delete --name ${{ vars.RESOURCE_NAME }} --yes

    # Checkout code
    - uses: actions/checkout@main

    - name: Provision Resources
      uses: azure/arm-deploy@v1
      if: always()
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        scope: subscription
        region: centralus
        template: ./TranscribeTranslateDemo.Infrastructure/main.bicep
        parameters: location=centralus commonResourceName=${{ vars.RESOURCE_NAME }}
        failOnStdErr: false
        deploymentName: bicep-ci-${{ github.run_id }}
