name: Static Web Apps Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - "TranscribeTranslateDemo.Web/**"
      - "TranscribeTranslateDemo.Shared/**"
      - ".github/workflows/web.yml"
  workflow_dispatch:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:

      # Log into Azure
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Get SWA Token
      id: swa-token
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: echo SWA_TOKEN=$(az staticwebapp secrets list --name ${{ vars.RESOURCE_NAME }}swa --query 'properties.apiKey') | tr -d '"' >> "$GITHUB_OUTPUT"

    - name: Get Function Key
      id: function-key
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: echo FUNCTION_KEY=$(az functionapp keys list --name ${{ vars.RESOURCE_NAME }}func --resource-group ${{ vars.RESOURCE_NAME }} --query 'masterKey') | tr -d '"' >> "$GITHUB_OUTPUT"
    
    - name: Set Function Key
      run: |
        pushd './TranscribeTranslateDemo.Web/wwwroot'
        sed -i 's/abcdefghijklmnopqrstuvwxyz/${{ steps.function-key.outputs.FUNCTION_KEY }}/g' appsettings.json
        popd

      # Checkout code
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ steps.swa-token.outputs.SWA_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
        action: "upload"
        ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
        app_location: "TranscribeTranslateDemo.Web" # App source code path
        api_location: "" # Api source code path - optional
        output_location: "wwwroot" # Built app content directory - optional
        ###### End of Repository/Build Configurations ######

    - name: Reset SWA Token
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: az staticwebapp secrets reset-api-key --name ${{ vars.RESOURCE_NAME }}swa --resource-group ${{ vars.RESOURCE_NAME }} --no-wait
